#install from github.com/sudar/Arduino-Makefile
ARDUINO_MK_DIR   = /home/cantora/install/Arduino-Makefile
BOARD_TAG        = atmega8
ARDUINO_PORT     = /dev/ttyUSB1

#ARDUINO_LIBS = SoftwareSerial

include $(ARDUINO_MK_DIR)/arduino-mk/Arduino.mk
